framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
             async:
               dsn: '%env(RABBITMQ_DSN)%'
               retry_strategy:
                 max_retries: 3
                 multiplier: 2

             failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            App\Message\CommentMessage: async
